default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf
        args: [--style=style.ini, -i, -r]
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        args: [--config=setup.cfg]
        additional_dependencies: [
            flake8-bugbear==22.10.27,
            pep8-naming==0.13.2,
            flake8-docstrings==1.6.0,
            flake8-builtins==2.0.1,
            flake8-quotes==3.3.1
        ]
